28.	Perform the following operations using Python on the Salaries.csv data set
a. Create data subsets
b. Merge Data
c. Sort Data
d. Transposing Data
e. Shape and reshape Data

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("Salaries.csv")
df.head()

rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

# a. Create Data Subsets

In [6]:
# Selecting specific columns
subset_columns = df[['rank', 'discipline', 'salary']]

In [8]:
# Selecting first 10 rows
subset_rows = df.iloc[:10]

In [10]:
# Condition-based subset: Salaries > 100000
high_salary = df[df['salary'] > 100000]

# b. Merge Data

In [13]:
# Splitting into two subsets
df1 = df.iloc[:5]
df2 = df.iloc[5:10]

In [15]:
# Merge vertically (row-wise)
merged_df = pd.concat([df1, df2], ignore_index=True)

In [17]:
# Merge horizontally (column-wise)
merged_columns = pd.concat([df1.reset_index(drop=True), df2.reset_index(drop=True)], axis=1)

# c. Sort Data

In [27]:
sorted_df = df.sort_values(by='salary', ascending=False)
print(sorted_df[['rank', 'salary']])

         rank  salary
0        Prof  186960
13       Prof  162200
72       Prof  161101
27       Prof  155865
31       Prof  155750
..        ...     ...
55   AsstProf   72500
71  AssocProf   71065
66   AsstProf   63100
54  AssocProf   62884
9        Prof   57800

[78 rows x 2 columns]


# d. Transpose Data

In [30]:
transposed = df.head().T
transposed

0      1       2       3       4
rank          Prof   Prof    Prof    Prof    Prof
discipline       B      A       A       A       B
phd             56     12      23      40      20
service         49      6      20      31      18
sex           Male   Male    Male    Male    Male
salary      186960  93000  110515  131205  104800

# e. Shape and Reshape Data

In [33]:
# Shape of dataset
print("Shape:", df.shape)

Shape: (78, 6)


In [35]:
# Reshape example: Convert part of the data to numpy and reshape
salary_array = df['salary'].head(12).values.reshape(4, 3)
print("Reshaped Salary Data (4x3):\n", salary_array)

Reshaped Salary Data (4x3):
 [[186960  93000 110515]
 [131205 104800 122400]
 [ 81285 126300  94350]
 [ 57800 128250 134778]]
